# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile', models.BigIntegerField()),
                ('customer_email', models.EmailField(max_length=50)),
                ('customer_age', models.IntegerField()),
                ('customer_sales', models.IntegerField()),
                ('customer_location', models.CharField(max_length=100)),
            ],
        ),
    ]
